words = ["Arcymag", "Abecadło", "Acerola", "Adrenalina", "Afrodyta", "Agat", "Aikido", "Akredytacja", "Akrobata",
         "Alchemia", "Bank", "Bateria", "Bitwa", "Biblioteka", "Biegacz", "Biuro", "Blok", "Boisko", "Boczek",
         "Bylina", "Cebula", "Cegła", "Cement", "Centrum", "Chmura", "Chodnik", "Choroba", "Chwila", "Ciepło",
         "Cisza", "Dach", "Dama", "Dalmierz", "Dziecko", "Dzień", "Działka", "Dzwonek", "Dźwięk", "Dźwig", "Dżins",
         "Ekran", "Ekwador", "Elektron", "Emocja", "Encyklopedia", "Energia", "Entuzjazm", "Epoka", "Erudyta",
         "Emisja", "Fabryka", "Fakt", "Fala", "Fantazja", "Faza", "Fenomen", "Ferie", "Festiwal", "Film", "Firma",
         "Gablotka", "Galaktyka", "Guma", "Garderoba", "Garnek", "Gazeta", "Geometria", "Geranium", "Głos", "Gmina",
         "Hala", "Hotel", "Haczyk", "Huragan", "Huta", "Hydepark", "Hymn", "Igła", "Iglak", "Impreza", "Incydent",
         "Indeks", "Informacja", "Ingerencja", "Inicjatywa", "Instytucja", "Interakcja", "Jabłko", "Jacht", "Jagoda",
         "Jakość", "Jarmark", "Jaskinia", "Jazda", "Jedwab", "Język", "Jezioro", "Kabina", "Kaczka", "Kaloria",
         "Kamień", "Kanał", "Kanapka", "Kapsuła", "Karate", "Karawan", "Karta", "Lampa", "Lasso", "Lato", "Lekcja",
         "Lekkoatleta", "Lemoniada", "Lew", "Liga", "Lina", "Lipsko", "Magia", "Magnes", "Majtki", "Majonez",
         "Makedonia", "Mama", "Manufaktura", "Marchewka", "Makaron", "Marka", "Nasiona", "Narty", "Nauka", "Niebo",
         "Niedziela", "Nieznajomy", "Noga", "Nowela", "Notatnik", "Numer", "Oaza", "Obrączka", "Obraz", "Ochrona",
         "Ochroniarz", "Ocena", "Odwaga", "Ogród", "Okno", "Okulary", "Pachnidło", "Pająk", "Pakiet", "Palma",
         "Pancernik", "Panel", "Papaja", "Papier", "Park", "Partia", "Rachunek", "Radio", "Rakieta", "Rabarbar",
         "Randka", "Ręka", "Reklama", "Relaks", "Rękawiczka", "Restaurant", "Sałatka", "Samorodek", "Samochód",
         "Satelita", "Sauna", "Sejm", "Sekretarka", "Sennik", "Serce", "Sesja", "Taktyka", "Tama", "Tarcza",
         "Telefon", "Teoria", "Termin", "Test", "Tkanina", "Towar", "Tolerancja", "Ucho", "Uczta", "Uczeń",
         "Uniwersytet", "Ulica", "Ugoda", "Unia", "Uroda", "Usługa", "Uśmiech", "Waga", "Walizka", "Waluta",
         "Wanna", "Wazon", "Wątek", "Wiatr", "Wieża", "Wieś", "Wino", "Zabawka", "Zamek", "Zdrowie", "Zaniedbanie",
         "Zapach", "Zegar", "Zielenina", "Zima", "Złoto"]